version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: online-shopping-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: online-shopping
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    ports:
      - "5428:5432" 

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
